[package]
name = "smart-contract-verifier-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smart-contract-verifier = { path = "../smart-contract-verifier" }
smart-contract-verifier-proto = { path = "../smart-contract-verifier-proto" }
sig-provider-extension = { path = "../sig-provider-extension", optional = true }

actix-web = "4"
actix-web-prom = "0.6"
amplify = { version = "3.13.0", features = ["derive"] }
anyhow = "1.0"
async-trait = "0.1"
blockscout-display-bytes = { version = "1.0" }
blockscout-service-launcher = { version = "0.9.0" }
bytes = "1.3"
config = "0.13"
cron = "0.11"
ethers-solc = "2.0.10"
ethers-core = "2.0.10"
futures = "0.3"
lazy_static = "1"
opentelemetry = { version = "0.18", features = ["rt-tokio"] }
opentelemetry-jaeger = { version = "0.17", features = ["rt-tokio"] }
prometheus = "0.13"
rust-s3 = "0.32"
serde = "1.0"
serde_json = "1.0"
serde_with = "2.1"
thiserror = "1.0"
tokio = { version = "1", features = ["rt-multi-thread"] }
tonic = "0.8"
tracing = "0.1"
tracing-opentelemetry = "0.18"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
url = "2.3"

[dev-dependencies]
ethers-solc = { version = "2.0.10", features = ["svm-solc"] }
blockscout-service-launcher = { version = "0.9.0" , features = ["test-server"]}
ethabi = "18.0"
pretty_assertions = "1.3"
reqwest = "0.11.13"
rstest = "0.18"