[package]
name = "zetachain-cctx-logic"
version = "0.1.0"
edition = "2021"


[dependencies]
zetachain-cctx-entity = { path = "../zetachain-cctx-entity" }
anyhow = "1.0"
async-trait = "0.1"
blockscout-display-bytes = "1.0"
tracing = "0.1"
uuid = { version = "1.13", features = ["v4"] }

sea-orm = { workspace = true, features = [
    "sqlx-postgres",
    "runtime-tokio-rustls",
    "macros",
    "postgres-array",
] }


## Uncomment this if needed
#ethabi = "18.0"
#ethers-core = "2.0.0"
futures = { workspace = true }
#hex = "0.4"
#keccak-hash = "0.10.0"
#lazy_static = "1"
#mismatch = "1.0"
#prometheus = "0.13"
reqwest = { workspace = true }
#semver = "1.0"
serde = { workspace = true }
governor.workspace = true
serde_json = "1.0"
#thiserror = "1.0"
tokio = { workspace = true }
#tonic = { version = "0.8", features = ["tls-roots"] }
#tracing-subscriber = { version = "0.3", features = ["env-filter"]}
base64 = { workspace = true }
chrono = { workspace = true }
async-stream = { workspace = true }
zetachain-cctx-proto = { path = "../zetachain-cctx-proto" }
[dev-dependencies]
blockscout-service-launcher = { workspace = true, features = [

    "test-database",
    "database-1",

] }
rand = "0.9.1"
pretty_assertions = "1.3"
zetachain-cctx-migration = { path = "../zetachain-cctx-migration" }
wiremock = {workspace = true}
