[[counters]]
id = "totalBlocks"
title = "Total Blocks"
update_schedule = "0 0 0,3,6,9,12,15,18,21 * * * *"

[[counters]]
id = "averageBlockTime"
title = "Average Block Time"
units = "s"

[[counters]]
id = "completedTxns"
title = "Completed Txns"
update_schedule = "0 0 0,3,6,9,12,15,18,21 * * * *"

[[counters]]
id = "totalAccounts"
title = "Total Accounts"

[[counters]]
id = "totalNativeCoinHolders"
title = "Total Native Coin Holders"

[[counters]]
id = "totalNativeCoinTransfers"
title = "Total Native Coin Transfers"

[[counters]]
id = "totalTokens"
title = "Total Tokens"

[[counters]]
id = "totalTxns"
title = "Total Txns"
update_schedule = "0 0 0,3,6,9,12,15,18,21 * * * *"


[[lines.sections]]
id = "accounts"
title = "Accounts"

[[lines.sections.charts]]
id = "activeAccounts"
title = "Active accounts"
description = "Active accounts number per period"

[[lines.sections.charts]]
id = "accountsGrowth"
title = "Accounts growth"
description = "Cumulative accounts number per period"


[[lines.sections]]
id = "transactions"
title = "Transactions"

[[lines.sections.charts]]
id = "averageTxnFee"
title = "Average transaction fee"
description = "The average amount in USD spent per transaction"

[[lines.sections.charts]]
id = "txnsFee"
title = "Transactions fees"
description = "Amount of tokens paid as fees"

[[lines.sections.charts]]
id = "newTxns"
title = "New transactions"
description = "New transactions number"

[[lines.sections.charts]]
id = "txnsGrowth"
title = "Transactions growth"
description = "Cumulative transactions number"


[[lines.sections]]
id = "blocks"
title = "Blocks"

[[lines.sections.charts]]
id = "newBlocks"
title = "New blocks"
description = "New blocks number"

[[lines.sections.charts]]
id = "averageBlockSize"
title = "Average block size"
description = "Average size of blocks in bytes"


[[lines.sections]]
id = "tokens"
title = "Tokens"

[[lines.sections.charts]]
id = "nativeCoinHoldersGrowth"
title = "Native coin holders growth"
description = "Cumulative token holders number for the period"

[[lines.sections.charts]]
id = "newNativeCoinTransfers"
title = "New native coins transfers"
description = "New token transfers number for the period"

[[lines.sections.charts]]
id = "nativeCoinSupply"
title = "Native coin circulating supply"
description = "Amount of token circulating supply for the period"


[[lines.sections]]
id = "gas"
title = "Gas"

[[lines.sections.charts]]
id = "averageGasLimit"
title = "Average gas limit"
description = "Average gas limit per block for the period"

[[lines.sections.charts]]
id = "gasUsedGrowth"
title = "Gas used growth"
description = "Cumulative gas used for the period"

[[lines.sections.charts]]
id = "averageGasPrice"
title = "Average gas price"
description = "Average gas price for the period (Gwei)"
