version: "3"
services:
  database:
    image: postgres:15
    container_name: 'eth-bytecode-db-postgres'
    restart: always
    environment:
      POSTGRES_PASSWORD: ''
      POSTGRES_USER: 'postgres'
      POSTGRES_HOST_AUTH_METHOD: 'trust'
  smart-contract-verifier:
    image: ghcr.io/blockscout/smart-contract-verifier:${SMART_CONTRACT_VERIFIER_DOCKER_TAG:-main}
    container_name: 'eth-bytecode-db-verifier'
    restart: always
    environment:
      SMART_CONTRACT_VERIFIER__SERVER__HTTP__ENABLED: false
      SMART_CONTRACT_VERIFIER__SERVER__GRPC__ENABLED: true
      SMART_CONTRACT_VERIFIER__SERVER__GRPC__ADDR: 0.0.0.0:8050
  eth-bytecode-db:
    ## you can build an image locally, or use pre-built images from registry
#    image: ghcr.io/blockscout/eth-bytecode-db:main
    build:
      context: ..
      dockerfile: ./eth-bytecode-db-server/Dockerfile
    container_name: 'eth-bytecode-db'
    restart: always
    depends_on:
      - database
      - smart-contract-verifier
    ports:
      - "8050:8050"
      - "8051:8051"
    environment:
      ## optional: if provided, would be used as a configuration file
      ETH_BYTECODE_DB__CONFIG: /app/config.toml
      ETH_BYTECODE_DB__VERIFIER__URI: http://smart-contract-verifier:8050
      ETH_BYTECODE_DB__DATABASE__URL: postgres://postgres:@database:5432/eth_bytecode_db
      ETH_BYTECODE_DB__DATABASE__CREATE_DATABASE: true
      ETH_BYTECODE_DB__DATABASE__RUN_MIGRATIONS: true
    env_file:
      ## optional: if provided, would overwrite values from configuration file
      - ./config/base.env
    volumes:
      ## optional: you can use default config or provide custom via file
      - ./config/base.toml:/app/config.toml
