version: "3"
services:
  verification:
    ## you can build an image locally, or use pre-built images from registry
    build: .
#    image: ghcr.io/blockscout/verification:latest
    ports:
      - "8043:8043"
    environment:
      ## optional: if provided, would be used as a configuration file
      - VERIFICATION__CONFIG=/app/config.toml
    env_file:
      ## optional: if provided, would overwrite values from configuration file
      - config/base.env
    volumes:
      ## optional: you can use default config or provide custom via file
      - ./config/base.toml:/app/config.toml
      ## optional: provide volume or folder to store compilers between launches
      - /tmp/compilers:/tmp/compilers