type: google.api.Service
config_version: 3

http:
  rules:
    #################### DomainsExtractor ####################
    - selector: blockscout.bens.v1.DomainsExtractor.GetDomain
      get: /api/v1/{chain_id}/domains/{name}

    - selector: blockscout.bens.v1.DomainsExtractor.ListDomainEvents
      get: /api/v1/{chain_id}/domains/{name}/events

    - selector: blockscout.bens.v1.DomainsExtractor.LookupDomainName
      post: /api/v1/{chain_id}/domains:lookup
      body: "*"

    - selector: blockscout.bens.v1.DomainsExtractor.LookupAddress
      post: /api/v1/{chain_id}/addresses:lookup
      body: "*"

    - selector: blockscout.bens.v1.DomainsExtractor.BatchResolveAddressNames
      post: /api/v1/{chain_id}/addresses:batch-resolve-names
      body: "*"

    #################### Health ####################

    - selector: blockscout.bens.v1.Health.Check
      get: /health
