type: google.api.Service
config_version: 3

http:
  rules:
    #################### DomainsExtractor ####################
    - selector: blockscout.bens.v1.DomainsExtractor.GetDomain
      get: /api/v1/{chain_id}/domains/{id}

    - selector: blockscout.bens.v1.DomainsExtractor.ListDomainEvents
      get: /api/v1/{chain_id}/domains/{domain_id}/events

    - selector: blockscout.bens.v1.DomainsExtractor.ResolveDomainName
      post: /api/v1/{chain_id}/domains:resolve
      body: "*"

    - selector: blockscout.bens.v1.DomainsExtractor.BatchResolveDomainNames
      post: /api/v1/{chain_id}/domains:batch-resolve
      body: "*"

    - selector: blockscout.bens.v1.DomainsExtractor.ResolveAddress
      post: /api/v1/{chain_id}/addresses:resolve
      body: "*"

    - selector: blockscout.bens.v1.DomainsExtractor.BatchSearchAddressNames
      post: /api/v1/{chain_id}/address-names:batch-search
      body: "*"

    #################### Health ####################

    - selector: blockscout.bens.v1.Health.Check
      get: /health
