type: google.api.Service
config_version: 3

http:
  rules:

    #################### MultichainNames ####################
    - selector: blockscout.bens.v1.MultichainDomains.GetDomainNameMultichain
      get: /api/v1/domains/{name}

    - selector: blockscout.bens.v1.MultichainDomains.ListDomainEventsMultichain
      get: /api/v1/domains/{name}/events

    - selector: blockscout.bens.v1.MultichainDomains.LookupDomainNameMultichain
      get: /api/v1/domains:lookup

    - selector: blockscout.bens.v1.MultichainDomains.LookupAddressMultichain
      get: /api/v1/addresses:lookup

    - selector: blockscout.bens.v1.MultichainDomains.GetAddressMultichain
      get: /api/v1/addresses/{address}

    - selector: blockscout.bens.v1.MultichainDomains.BatchResolveAddressesMultichain
      post: /api/v1/addresses:batch-resolve
      body: "*"

    - selector: blockscout.bens.v1.MultichainDomains.GetMutlichainProtocols
      get: /api/v1/protocols

    #################### DomainsExtractor ####################
    - selector: blockscout.bens.v1.DomainsExtractor.GetDomain
      get: /api/v1/{chain_id}/domains/{name}

    - selector: blockscout.bens.v1.DomainsExtractor.ListDomainEvents
      get: /api/v1/{chain_id}/domains/{name}/events

    - selector: blockscout.bens.v1.DomainsExtractor.LookupDomainName
      get: /api/v1/{chain_id}/domains:lookup

    - selector: blockscout.bens.v1.DomainsExtractor.LookupAddress
      get: /api/v1/{chain_id}/addresses:lookup

    - selector: blockscout.bens.v1.DomainsExtractor.GetAddress
      get: /api/v1/{chain_id}/addresses/{address}

    - selector: blockscout.bens.v1.DomainsExtractor.BatchResolveAddressNames
      post: /api/v1/{chain_id}/addresses:batch-resolve-names
      body: "*"

    - selector: blockscout.bens.v1.DomainsExtractor.GetProtocols
      get: /api/v1/{chain_id}/protocols

    #################### Health ####################

    - selector: blockscout.bens.v1.Health.Check
      get: /health
