[workspace]
resolver = "2"
members = [
    "scoutcloud",
    "scoutcloud-entity",
    "scoutcloud-migration",
    "scoutcloud-proto",
]

[workspace.dependencies]
blockscout-service-launcher = "0.11.0"
