[package]
name = "env-docs-generation"
version = "0.1.0"
edition = "2024"

[dependencies]
user-ops-indexer-server = { path = "../user-ops-indexer-server" }
env-collector = { git = "https://github.com/blockscout/blockscout-rs", rev = "18135aff022e0f419505ce1d7000a9f2048e5222" } # patched version from PR branch
