stats:
    environment:
        STATS__DATABASE_URL:
            _default: ENC[AES256_GCM,data:Ant9ECvw21d2kdH4+NfWSVunb7nVbbT/t4L1NSFMWmtsVyDqyMLLzI5KhDhLhBMr3zYgBK20,iv:CD8NhfFLOQvyb7fAijScavC1viB4RPbUcvYgDkWnTlw=,tag:qriVEHu2SuyFiRimezVYMQ==,type:str]
        STATS__BLOCKSCOUT_DB_URL:
            _default: ENC[AES256_GCM,data:JlamJ2gFbcSn5C7xPbOZvxbMccK3pPrEgaLk1g98Db4s3FHQ0b+wulLx2jER89hivGDOj0s3iryPhDkfio54aKTpO1x0w8jiplTVDBI0GzP9QQQ0KXSvZgCyWZ2UY5NTkg==,iv:vPNPB41a7eIKCH/68OM7H3VRnJCpk4BhT6bsEl0HICM=,tag:vyto24YHvIspU5KxoyUvPg==,type:str]
postgres:
    environment:
        POSTGRES_USER:
            _default: ENC[AES256_GCM,data:xG9FGCAQD5s=,iv:ZDXo4emrFDfwwQe73LjOGwFt43c6Lz9GouDD6X6U+hs=,tag:wAOR1VrT+VqUVUl/wLCHWw==,type:str]
        POSTGRES_PASSWORD:
            _default: ENC[AES256_GCM,data:v5INnogIzM11nGDf,iv:LSdodsS4JeV2ORa84w47YqIUo3r0ypKnpg35TTZmVFY=,tag:/LW1BswbjY+ip6sFR5DnOQ==,type:str]
        POSTGRES_DB:
            _default: ENC[AES256_GCM,data:t7E3sbE=,iv:N8XwqKLy+RVsatzK+YU7D6k/e3MKWhTmx2jIAyA+2YE=,tag:btZojELAGBgf/EcoT0Ulmw==,type:str]
        POSTGRES_HOST_AUTH_METHOD:
            _default: ENC[AES256_GCM,data:7RhBddA=,iv:8ZNr54pRbHn/sWz8QxExZFuV/vl44qiABrCa1uIVPQE=,tag:IiRkFeO9neyLQAhURn41BQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-12-21T16:16:27Z"
    mac: ENC[AES256_GCM,data:pFYJa6ytMhxh/hvYvaMz3cqQlgOcxsfo7YrzeKpf0VfgpkAJjsxpFM+iCrSsC/6A05h3y7Ueu1ks/cGD5GRvVz3PJ+ChylYfi6JBRXe1zB5xTUHUEQxr/3WnrQFQFAGEh8NTAthm8u4NZhiBQtDjIMA8yozhEIxYrfjGlzADQYQ=,iv:Ugz0MXKggbqCoOe/+uPn9wDaDw9t1H8jQVdTdUso23o=,tag:70FvkgGDyiXDKsR2D6DsnA==,type:str]
    pgp:
        - created_at: "2022-12-02T15:43:31Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA1MXzg1c4SMLAQf/aJcz2VW7G/KGdg0DjQm+X3zhEAoB0x0oKXiJX0zc7oOE
            jz4/LaK1+W4UgC2Ecu6S0AzHdAkdddQqivXv2hNWvwOGaYr2F5nuASCbzLoUpgmu
            cImqfeQPwCfRsyKvEpp58bBfUljioXiOu8r41ZssF3j0V+t3Oc3oghb7XifV8v7M
            Pv2QZF+5qIgwzLv5ycegd0YA98omcYwIOOn9PTyFt9mtjhAowBIwfacE673y86xq
            T9McMrwGwMAXb5AbisDSUOBebQ9igRA6uUZqwb5RQznG8yOBS1aKnLPoICh8hwWu
            gbGEp7KMTQNri1LdoUr9NwOpXN0HgXoCOffUpiP3FdJeAQjxNvaSsgDfg7C28pRq
            N1t78mb3abahg0SPX4Km2DCN9ALEd6I46usaM5oI4ycfaHFA+9+yDGt3OmD/BfX6
            Ub1IxSGZQKkZFmANxxSc8GOU1DrkdDGO2I1Q8XAMag==
            =BptU
            -----END PGP MESSAGE-----
          fp: 99E83B7490B1A9F51781E6055317CE0D5CE1230B
    unencrypted_suffix: _unencrypted
    version: 3.7.3
