[package]
name = "job-queue"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sea-orm = { version = "^0", optional = true }
sea-orm-migration = { version = "^0", optional = true }

[features]
entity = [
    "dep:sea-orm",
]
logic = [
    "entity",
]
migration = [
    "dep:sea-orm-migration",
]

