[workspace]
resolver = "2"
members = [
    "user-ops-indexer-entity",
    "user-ops-indexer-logic",
    "user-ops-indexer-migration",
    "user-ops-indexer-proto",
    "user-ops-indexer-server",
]

[workspace.dependencies]
blockscout-service-launcher = "0.16.2"