[workspace]
resolver = "2"
members = [
    "user-ops-indexer-entity",
    "user-ops-indexer-logic",
    "user-ops-indexer-migration",
    "user-ops-indexer-proto",
    "user-ops-indexer-server",
]

[workspace.dependencies]
alloy = "1.1"
blockscout-service-launcher = "0.20.0"
tonic = "0.12"
