[package]
name = "env-docs-generation"
version = "0.1.0"
edition = "2024"

[dependencies]
env-collector = { git = "https://github.com/blockscout/blockscout-rs", rev = "1e9d3c8a06f82626525217f6c2c51c1368868cd8" } # latest almost merged PR version
stats-server = { path = "../stats-server" }
