[package]
name = "user-ops-indexer-proto"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-prost = "0.1.0"
actix-prost-macros = "0.1.0"
actix-web = "4"
prost = "0.13"
prost-wkt = "0.6"
prost-wkt-types = "0.6"
tonic = { workspace = true }
serde = { version = "1", features = ["derive"] }
serde_with = { version = "2.0", features = ["hex", "base64"] }
async-trait = "0.1"

[build-dependencies]
actix-prost-build = "0.1.0"
tonic-build = "0.12"
prost-build = "0.13"
