[package]
name = "sig-provider-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sig-provider = { path = "../sig-provider" }
sig-provider-proto = { path = "../sig-provider-proto" }
async-trait = "0.1"
actix-web = "4"
tonic = "0.8"
serde = { version = "1", features = ["derive"] }
serde_with = { version = "2.0", features = ["hex", "base64"] }
bytes = "1.2"
tokio = { version = "1", features = ["rt-multi-thread"] }
config = "0.13"
env_logger = "0.9"
tracing = "0.1"
futures = "0.3"
anyhow = "1.0"
url = { version = "2", features = ["serde"] }
hex = "0.4"

[dev-dependencies]
http = "0.2"
httpmock = "0.6"
pretty_assertions = "1.3"
serde_json = "1.0"
