[package]
name = "scoutcloud"
version = "0.1.0"
edition = "2021"


[dependencies]
scoutcloud-entity = { path = "../scoutcloud-entity" }
anyhow = "1.0"
blockscout-display-bytes = "1.0"
tracing = "0.1"
thiserror = "1.0"
hex = "0.4"
foundry-compilers = "0.3.9"
serde_json = "1.0.108"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
sea-orm = { version = "0.12.2", features = [
    "sqlx-postgres",
    "runtime-tokio-rustls",
    "macros",
    "postgres-array",
] }
octocrab = { version = "0.35.0", features = ["rustls-webpki-tokio"] }
serde = { version = "1.0.197", features = ["serde_derive", "derive"] }
tracing-subscriber = "0.3.18"
httpmock = "0.7.0"
scoutcloud-proto = { path = "../scoutcloud-proto" }
scoutcloud-migration = { path = "../scoutcloud-migration" }
actix-web = "4.2"
async-trait = "0.1"
blockscout-service-launcher = { version = "0.10.1", features = [ "database-0_12" ] }
config = "0.13"
tonic = "0.8"
chrono = "0.4.35"
paste = "1.0"
url = "2.5.0"
serde_yaml = "0.9.34"
lazy_static = "1.4.0"
ethers = { version = "2.0.14", features = ["ws"] }
json_dotpath = "1.1.0"
serde_plain = "1.0.2"
num-bigint = { version = "0.4.4", features = ["serde"] }
slug = "0.1.5"
convert-trait = { git = "https://github.com/blockscout/actix-prost", tag="v1.0.0" }
rust_decimal = "1.35.0"
fang = { version = "0.10.4" , features = ["asynk", "derive-error" ], default-features = false }


[dev-dependencies]
blockscout-service-launcher = { version = "0.10.1", features = [
    "test-database", "database-0_12", "test-server"
] }
serial_test = "3.1.1"
scoutcloud-migration = {path = "../scoutcloud-migration"}
pretty_assertions = "1.3"
reqwest = { version = "0.11", features = ["json"]}

