swagger: "2.0"
info:
  title: v1/tac-operation-lifecycle.proto
  version: version not set
tags:
  - name: TacService
  - name: TacStatistic
  - name: Health
consumes:
  - application/json
produces:
  - application/json
paths:
  /api/v1/TacService:getOperationByTransaction:
    post:
      operationId: TacService_GetOperationByTransaction
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1OperationDetails'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1GetOperationByTxHashRequest'
      tags:
        - TacService
  /api/v1/TacService:getOperationDetails:
    post:
      operationId: TacService_GetOperationDetails
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1OperationDetails'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1GetOperationDetailsRequest'
      tags:
        - TacService
  /api/v1/TacService:getOperations:
    post:
      operationId: TacService_GetOperations
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1OperationsResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1GetOperationsRequest'
      tags:
        - TacService
  /api/v1/stat:
    post:
      operationId: TacStatistic_GetIndexerStatistics
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1GetIndexerStatisticResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      tags:
        - TacStatistic
  /health:
    get:
      summary: |-
        If the requested service is unknown, the call will fail with status
        NOT_FOUND.
      operationId: Health_Check
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1HealthCheckResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: service
          in: query
          required: false
          type: string
      tags:
        - Health
definitions:
  HealthCheckResponseServingStatus:
    type: string
    enum:
      - UNKNOWN
      - SERVING
      - NOT_SERVING
      - SERVICE_UNKNOWN
    default: UNKNOWN
    description: ' - SERVICE_UNKNOWN: Used only by the Watch method.'
  OperationRelatedTransactionBlockchainType:
    type: string
    enum:
      - TAC
      - TON
      - Unknown
    default: TAC
  OperationStageStageType:
    type: string
    enum:
      - CollectedInTAC
      - IncludedInTACConsensus
      - ExecutedInTAC
      - CollectedInTON
      - IncludedInTONConsensus
      - ExecutedInTON
    default: CollectedInTAC
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  rpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/protobufAny'
  v1GetIndexerStatisticResponse:
    type: object
    properties:
      timestamp:
        type: string
        format: uint64
      watermark:
        type: string
        format: uint64
      realtime_from:
        type: string
        format: uint64
      first_timestamp:
        type: string
        format: uint64
      last_timestamp:
        type: string
        format: uint64
      total_intervals:
        type: string
        format: uint64
      failed_intervals:
        type: string
        format: uint64
      total_pending_intervals:
        type: string
        format: uint64
      historical_pending_intervals:
        type: string
        format: uint64
      realtime_pending_intervals:
        type: string
        format: uint64
      historical_processed_period:
        type: string
        format: uint64
      realtime_processed_period:
        type: string
        format: uint64
      historical_sync_completeness:
        type: number
        format: double
      realtime_sync_completeness:
        type: number
        format: double
  v1GetOperationByTxHashRequest:
    type: object
    properties:
      tx_hash:
        type: string
  v1GetOperationDetailsRequest:
    type: object
    properties:
      operation_id:
        type: string
  v1GetOperationsRequest:
    type: object
    properties:
      page_timestamp:
        type: string
        format: uint64
      page_size:
        type: string
        format: uint64
  v1HealthCheckResponse:
    type: object
    properties:
      status:
        $ref: '#/definitions/HealthCheckResponseServingStatus'
  v1OperationBriefDetails:
    type: object
    properties:
      operation_id:
        type: string
      type:
        $ref: '#/definitions/v1OperationType'
      timestamp:
        type: string
        format: uint64
      sender:
        type: string
  v1OperationDetails:
    type: object
    properties:
      operation_id:
        type: string
      type:
        $ref: '#/definitions/v1OperationType'
      timestamp:
        type: string
        format: uint64
      sender:
        type: string
      status_history:
        type: array
        items:
          type: object
          $ref: '#/definitions/v1OperationStage'
  v1OperationRelatedTransaction:
    type: object
    properties:
      hash:
        type: string
      type:
        $ref: '#/definitions/OperationRelatedTransactionBlockchainType'
  v1OperationStage:
    type: object
    properties:
      type:
        $ref: '#/definitions/OperationStageStageType'
      is_exist:
        type: boolean
      is_success:
        type: boolean
      timestamp:
        type: string
        format: uint64
      transactions:
        type: array
        items:
          type: object
          $ref: '#/definitions/v1OperationRelatedTransaction'
      note:
        type: string
  v1OperationType:
    type: string
    enum:
      - Error
      - Pending
      - TonTacTon
      - TacTon
      - TonTac
      - Rollback
      - Unknown
    default: Error
  v1OperationsResponse:
    type: object
    properties:
      operations:
        type: array
        items:
          type: object
          $ref: '#/definitions/v1OperationBriefDetails'
      next_page_params:
        $ref: '#/definitions/v1Pagination'
  v1Pagination:
    type: object
    properties:
      page_timestamp:
        type: string
        format: uint64
      page_size:
        type: integer
        format: int64
