[package]
name = "zetachain-cctx-server"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "zetachain-cctx-server"
path = "src/main.rs"


[[bin]]
name = "check-envs"
path = "src/check-envs.rs"


[dependencies]
env-collector = { git = "https://github.com/blockscout/blockscout-rs", rev = "26eed65" }
zetachain-cctx-proto = { path = "../zetachain-cctx-proto" }
zetachain-cctx-logic = { path = "../zetachain-cctx-logic" }
zetachain-cctx-migration = { path = "../zetachain-cctx-migration" }
actix-web = "4.2"
anyhow = "1.0"
async-trait = "0.1"
blockscout-service-launcher = { workspace = true, features = ["database-1" ] }
config = { workspace = true }
sea-orm = { workspace = true }
serde = "1.0"
serde_json = "1.0.96"
tokio = { version = "1.23", features = [ "rt-multi-thread", "macros" ] }
tonic = { workspace = true }
tracing = "0.1"
actix-web-actors = "4.0"
actix = "0.13"
uuid = { version = "1.13", features = ["v4"] }

# # Uncomment if needed
# ethers = "2.0.0"
# blockscout-display-bytes = "1.0"
# serde_with = "2.1"


[dev-dependencies]
blockscout-service-launcher = { workspace = true, features = [ "test-server","test-database"] }
pretty_assertions = "1.3"
reqwest = { version = "0.12", features = ["json"]}
wiremock = "0.6"
chrono = "0.4"
zetachain-cctx-entity = { path = "../zetachain-cctx-entity" }
uuid = { version = "1.13", features = ["v4"] }
# # Uncomment if needed
# mockall = "0.11"
# bytes = "1.5.0"
# hex = "0.4.3"
# rand = "0.8"
# rstest = "0.18.2"
# sea-orm = { version = "*", features = [ "sqlx-sqlite" ]}
# tokio-stream = { version = "0.1", features = ["net"] }
