[package]
name = "proxy-verifier-proto"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-prost = { git = "https://github.com/blockscout/actix-prost" }
actix-prost-macros = { git = "https://github.com/blockscout/actix-prost" }
prost = "0.11"
serde = { version = "1" }
serde_with = { version = "2.0" }
tonic = "0.8"

[build-dependencies]
actix-prost-build = { git = "https://github.com/blockscout/actix-prost" }
prost-build = "0.11"
tonic-build = "0.8"
