[package]
name = "sig-provider"
version = "0.1.0"
edition = "2021"

[dependencies]
sig-provider-proto = { path = "../sig-provider-proto" }
tokio = "1"
async-trait = "0.1"
anyhow = "1.0"
tracing = "0.1"
futures = "0.3"
url = { version = "2", features = ["serde"] }
reqwest = { version = "0.11", features = ["json"] }
reqwest-middleware = "0.1"
reqwest-retry = "0.1"
hex = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
ethabi = "17"
mockall = "0.11"
itertools = "0.10"
async-recursion = "1.0.0"

[dev-dependencies]
pretty_assertions = "1.3"
rstest = "0.17.0"
