[package]
name = "scoutcloud-proto"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-prost = { git = "https://github.com/blockscout/actix-prost", tag="v1.0.0" }
actix-prost-macros = { git = "https://github.com/blockscout/actix-prost", tag="v1.0.0" }
convert-trait = { git = "https://github.com/blockscout/actix-prost", tag="v1.0.0" }
prost = "0.11"
serde = { version = "1" }
serde_with = { version = "3.6" }
tonic = "0.8"
url = { version = "2", features = ["serde"] }

[build-dependencies]
actix-prost-build = { git = "https://github.com/blockscout/actix-prost", branch = "lok52/derive-option", features = [
    "conversions",
] }
prost-build = "0.11"
tonic-build = "0.8"
