swagger: "2.0"
info:
  title: v1/scoutcloud.proto
  version: version not set
tags:
  - name: Scoutcloud
  - name: Health
consumes:
  - application/json
produces:
  - application/json
paths:
  /api/v1/deployments/{deployment_id}:
    get:
      operationId: Scoutcloud_GetDeployment
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1Deployment'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: deployment_id
          in: path
          required: true
          type: string
      tags:
        - Scoutcloud
  /api/v1/instances:
    get:
      operationId: Scoutcloud_ListInstances
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1ListInstancesResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      tags:
        - Scoutcloud
    post:
      operationId: Scoutcloud_CreateInstance
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1CreateInstanceResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1CreateInstanceRequest'
      tags:
        - Scoutcloud
  /api/v1/instances/{instance_id}:
    get:
      operationId: Scoutcloud_GetInstance
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1Instance'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: instance_id
          in: path
          required: true
          type: string
      tags:
        - Scoutcloud
  /api/v1/instances/{instance_id}/config:
    put:
      operationId: Scoutcloud_UpdateConfig
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1UpdateConfigResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: instance_id
          in: path
          required: true
          type: string
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/ScoutcloudUpdateConfigBody'
      tags:
        - Scoutcloud
    patch:
      operationId: Scoutcloud_UpdateConfigPartial
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1UpdateConfigResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: instance_id
          in: path
          required: true
          type: string
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/ScoutcloudUpdateConfigPartialBody'
      tags:
        - Scoutcloud
  /api/v1/instances/{instance_id}/deployments:
    get:
      operationId: Scoutcloud_ListDeployments
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1ListDeploymentsResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: instance_id
          in: path
          required: true
          type: string
      tags:
        - Scoutcloud
  /api/v1/instances/{instance_id}/deployments/current:
    get:
      operationId: Scoutcloud_GetCurrentDeployment
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1Deployment'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: instance_id
          in: path
          required: true
          type: string
      tags:
        - Scoutcloud
  /api/v1/instances/{instance_id}/status:update:
    post:
      operationId: Scoutcloud_UpdateInstanceStatus
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1UpdateInstanceStatusResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: instance_id
          in: path
          required: true
          type: string
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/ScoutcloudUpdateInstanceStatusBody'
      tags:
        - Scoutcloud
  /api/v1/users/profile:
    get:
      operationId: Scoutcloud_GetProfile
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1UserProfile'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      tags:
        - Scoutcloud
  /health:
    get:
      summary: |-
        If the requested service is unknown, the call will fail with status
        NOT_FOUND.
      operationId: Health_Check
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1HealthCheckResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: service
          in: query
          required: false
          type: string
      tags:
        - Health
definitions:
  HealthCheckResponseServingStatus:
    type: string
    enum:
      - UNKNOWN
      - SERVING
      - NOT_SERVING
      - SERVICE_UNKNOWN
    default: UNKNOWN
    description: ' - SERVICE_UNKNOWN: Used only by the Watch method.'
  ScoutcloudUpdateConfigBody:
    type: object
    properties:
      config:
        $ref: '#/definitions/v1DeployConfig'
  ScoutcloudUpdateConfigPartialBody:
    type: object
    properties:
      config:
        $ref: '#/definitions/v1DeployConfigPartial'
  ScoutcloudUpdateInstanceStatusBody:
    type: object
    properties:
      action:
        $ref: '#/definitions/v1UpdateInstanceAction'
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  rpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/protobufAny'
  v1CreateInstanceRequest:
    type: object
    properties:
      name:
        type: string
      config:
        $ref: '#/definitions/v1DeployConfig'
        title: initial config
  v1CreateInstanceResponse:
    type: object
    properties:
      instance_id:
        type: string
  v1DeployConfig:
    type: object
    properties:
      rpc_url:
        type: string
      server_size:
        type: string
      chain_type:
        type: string
      node_type:
        type: string
      chain_id:
        type: string
      token_symbol:
        type: string
      instance_url:
        type: string
      logo_url:
        type: string
      chain_name:
        type: string
      icon_url:
        type: string
      homeplate_background:
        type: string
      homeplate_text_color:
        type: string
      is_testnet:
        type: boolean
  v1DeployConfigPartial:
    type: object
    properties:
      rpc_url:
        type: string
      server_size:
        type: string
      chain_type:
        type: string
      node_type:
        type: string
      chain_id:
        type: string
      token_symbol:
        type: string
      instance_url:
        type: string
      logo_url:
        type: string
      chain_name:
        type: string
      icon_url:
        type: string
      homeplate_background:
        type: string
      homeplate_text_color:
        type: string
      is_testnet:
        type: boolean
  v1Deployment:
    type: object
    properties:
      deployment_id:
        type: string
      instance_id:
        type: string
      status:
        $ref: '#/definitions/v1DeploymentStatus'
      error:
        type: string
      created_at:
        type: string
      started_at:
        type: string
      finished_at:
        type: string
      config:
        $ref: '#/definitions/v1DeployConfig'
      blockscout_url:
        type: string
      total_cost:
        type: string
  v1DeploymentStatus:
    type: string
    enum:
      - NO_STATUS
      - CREATED
      - PENDING
      - RUNNING
      - STOPPING
      - STOPPED
      - FAILED
    default: NO_STATUS
  v1HealthCheckResponse:
    type: object
    properties:
      status:
        $ref: '#/definitions/HealthCheckResponseServingStatus'
  v1Instance:
    type: object
    properties:
      instance_id:
        type: string
      deployment_id:
        type: string
      name:
        type: string
      slug:
        type: string
      created_at:
        type: string
      config:
        $ref: '#/definitions/v1DeployConfig'
      deployment_status:
        $ref: '#/definitions/v1DeploymentStatus'
  v1ListDeploymentsResponse:
    type: object
    properties:
      items:
        type: array
        items:
          type: object
          $ref: '#/definitions/v1Deployment'
  v1ListInstancesResponse:
    type: object
    properties:
      items:
        type: array
        items:
          type: object
          $ref: '#/definitions/v1Instance'
  v1UpdateConfigResponse:
    type: object
    properties:
      config:
        $ref: '#/definitions/v1DeployConfig'
  v1UpdateInstanceAction:
    type: string
    enum:
      - START
      - STOP
      - RESTART
    default: START
  v1UpdateInstanceStatusResponse:
    type: object
    properties:
      status:
        $ref: '#/definitions/v1DeploymentStatus'
      deployment_id:
        type: string
  v1UserAction:
    type: object
    properties:
      action:
        type: string
      instance_id:
        type: string
      timestamp:
        type: string
  v1UserProfile:
    type: object
    properties:
      email:
        type: string
      project_title:
        type: string
      created_at:
        type: string
      balance:
        type: string
      recent_actions:
        type: array
        items:
          type: object
          $ref: '#/definitions/v1UserAction'
