[package]
name = "verifier-alliance-database"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
blockscout-display-bytes = { workspace = true }
keccak-hash = { workspace = true }
sea-orm = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
sha3 = { workspace = true }
strum = { workspace = true }
verification-common-v1 = { workspace = true }
verifier-alliance-entity-v1 = { workspace = true }

[dev-dependencies]
blockscout-service-launcher = { workspace = true, features = ["test-database"] }
pretty_assertions = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
tokio = { workspace = true, features = ["macros"] }
verifier-alliance-migration-v1 = { workspace = true }
