[package]
name = "tac-operation-lifecycle-proto"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-prost = { git = "https://github.com/blockscout/actix-prost" }
actix-prost-macros = { git = "https://github.com/blockscout/actix-prost" }
actix-web = { workspace = true }
prost = { workspace = true }
serde = { workspace = true }
serde_with = { workspace = true }
tonic = { workspace = true }

[build-dependencies]
actix-prost-build = { git = "https://github.com/blockscout/actix-prost" }
prost-build = { workspace = true }
tonic-build = { workspace = true }
