[package]
name = "stats-proto"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-prost = { git = "https://github.com/blockscout/actix-prost" }
actix-prost-macros = { git = "https://github.com/blockscout/actix-prost" }
actix-web = "4"
prost = "0.11"
tonic = { workspace = true }
serde = { version = "1", features = ["derive"] }
serde_with = { version = "3", features = ["hex", "base64"] }
async-trait = "0.1"

[dev-dependencies]
serde_json = "1.0"

[build-dependencies]
actix-prost-build = { git = "https://github.com/blockscout/actix-prost" }
tonic-build = "0.8"
prost-build = "0.11"
