[package]
name = "stats-proto"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-prost = "0.1.0"
actix-prost-macros = "0.1.0"
actix-web = "4"
async-trait = "0.1"
prost = "0.13"
serde = { version = "1", features = ["derive"] }
serde_with = { version = "3", features = ["hex", "base64"] }
tonic = "0.12"

[build-dependencies]
actix-prost-build = "0.1.0"
prost-build = "0.13"
tonic-build = "0.12"

[dev-dependencies]
serde_json = { workspace = true }
