[package]
name = "interchain-indexer-logic"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
blockscout-display-bytes = { workspace = true }
## Uncomment this if needed
#ethabi = { workspace = true }
#ethers-core = { workspace = true }
futures = { workspace = true }
governor = { workspace = true }
interchain-indexer-entity = { workspace = true }
parking_lot = { workspace = true }
sea-orm = { workspace = true, features = [
    "sqlx-postgres",
    "runtime-tokio-rustls",
    "macros",
    "postgres-array",
] }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
#hex = { workspace = true }
#keccak-hash = { workspace = true }
#lazy_static = { workspace = true }
#mismatch = { workspace = true }
#prometheus = { workspace = true }
#reqwest = { workspace = true }
#semver = { workspace = true }
#serde = { workspace = true }
#serde_json = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }
#tonic = { workspace = true, features = ["tls-roots"] }
#tracing-subscriber = { workspace = true, features = ["env-filter"]}

[dev-dependencies]
blockscout-service-launcher = { workspace = true, features = [ 
    
    "test-database", "database-1"
    
] }
interchain-indexer-migration = { workspace = true }
pretty_assertions = { workspace = true }
rstest = { workspace = true }
