[package]
name = "interchain-indexer-logic"
version = "0.1.0"
edition = "2024"

[features]
test-utils = []

[dependencies]
alloy = { workspace = true }
alloy-json-rpc = { workspace = true }
anyhow = { workspace = true }
async-stream = { workspace = true }
async-trait = { workspace = true }
base64 = { workspace = true }
blockscout-display-bytes = { workspace = true }
bs58 = { workspace = true }
chrono = { workspace = true }
dashmap = { workspace = true }
futures = { workspace = true }
governor = { workspace = true }
hex = { workspace = true }
hex-literal = { workspace = true }
interchain-indexer-entity = { workspace = true }
interchain-indexer-proto = { workspace = true }
itertools = { workspace = true }
lazy_static = { workspace = true }
moka = { workspace = true }
parking_lot = { workspace = true }
prometheus = { workspace = true }
rand = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
reqwest-middleware = { workspace = true }
reqwest-retry = { workspace = true }
sea-orm = { workspace = true, features = [
    "sqlx-postgres",
    "runtime-tokio-rustls",
    "macros",
    "postgres-array",
] }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
tower = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
bon = { workspace = true }

[dev-dependencies]
blockscout-service-launcher = { workspace = true, features = [
    "test-database",
    "database-1",
] }
interchain-indexer-migration = { workspace = true }
pretty_assertions = { workspace = true }
rstest = { workspace = true }
