[package]
name = "interchain-indexer-logic"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy = { workspace = true }
anyhow = { workspace = true }
blockscout-display-bytes = { workspace = true }
interchain-indexer-entity = { workspace = true }

sea-orm = { workspace = true, features = [
    "sqlx-postgres",
    "runtime-tokio-rustls",
    "macros",
    "postgres-array",
] }
thiserror = { workspace = true }
## Uncomment this if needed
#ethabi = { workspace = true }
#ethers-core = { workspace = true }
futures = { version = "0.3" }
hex = { version = "0.4" }
hex-literal = { version = "0.4" }
chrono = { version = "0.4" }
async-stream = { version = "0.3" }
#keccak-hash = { workspace = true }
#lazy_static = { workspace = true }
#mismatch = { workspace = true }
#prometheus = { workspace = true }
#reqwest = { workspace = true }
#semver = { workspace = true }
#serde = { workspace = true }
#serde_json = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }
#tonic = { workspace = true, features = ["tls-roots"] }
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }

[dev-dependencies]
blockscout-service-launcher = { workspace = true, features = [

    "test-database",
    "database-1",

] }
interchain-indexer-migration = { workspace = true }
pretty_assertions = { workspace = true }
rstest = { workspace = true }
